-- WARNING: only run this script if you know what you are doing.
-- If you are an energyPATHWAYS user it has likely already been run against your database and does not need
-- to be run again. If you're looking in this directory, you probably want to use delete_orphans.py instead.

-- Fix some broken or missing constraints
ALTER TABLE "DemandFuelSwitchingMeasuresEnergyIntensity" DROP CONSTRAINT "DemandFuelSwitchingMeasuresEnergyIntensity_id_fkey", ADD CONSTRAINT "DemandFuelSwitchingMeasuresEnergyIntensity_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandFuelSwitchingMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandFuelSwitchingMeasurePackages" DROP CONSTRAINT "DemandFuelSwitchingMeasurePackages_id_fkey", ADD CONSTRAINT "DemandFuelSwitchingMeasurePackages_subsector_id_fkey" FOREIGN KEY (subsector_id) REFERENCES "DemandSubsectors"(id);
ALTER TABLE "DemandStates" ADD CONSTRAINT "DemandStates_flexible_load_package_id_fkey" FOREIGN KEY (flexible_load_package_id) REFERENCES "DemandFlexibleLoadMeasurePackages"(id);

-- Change a bunch of other constraints to ON DELETE CASCADE to make it simpler to delete things that go together
ALTER TABLE "BlendNodeBlendMeasurePackagesData" DROP CONSTRAINT "BlendNodeBlendMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "BlendNodeBlendMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "BlendNodeBlendMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "BlendNodeBlendMeasuresData" DROP CONSTRAINT "BlendNodeBlendMeasuresData_parent_id_fkey", ADD CONSTRAINT "BlendNodeBlendMeasuresData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "BlendNodeBlendMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandCasesData" DROP CONSTRAINT "DemandCasesData_demand_case_id_fkey", ADD CONSTRAINT "DemandCasesData_demand_case_id_fkey" FOREIGN KEY (demand_case_id) REFERENCES "DemandCases"(id) ON DELETE CASCADE;
ALTER TABLE "DemandEnergyEfficiencyMeasurePackagesData" DROP CONSTRAINT "DemandEnergyEfficiencyMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "DemandEnergyEfficiencyMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "DemandEnergyEfficiencyMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "DemandEnergyEfficiencyMeasuresCost" DROP CONSTRAINT "DemandEnergyEfficiencyMeasuresCost_parent_id_fkey", ADD CONSTRAINT "DemandEnergyEfficiencyMeasuresCost_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandEnergyEfficiencyMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandEnergyEfficiencyMeasuresCostData" DROP CONSTRAINT "DemandEnergyEfficiencyMeasuresCostData_parent_id_fkey", ADD CONSTRAINT "DemandEnergyEfficiencyMeasuresCostData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandEnergyEfficiencyMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandEnergyEfficiencyMeasuresData" DROP CONSTRAINT "DemandEnergyEfficiencyMeasuresData_parent_id_fkey", ADD CONSTRAINT "DemandEnergyEfficiencyMeasuresData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandEnergyEfficiencyMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandFlexibleLoadMeasurePackagesData" DROP CONSTRAINT "DemandFlexibleLoadMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "DemandFlexibleLoadMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "DemandFlexibleLoadMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "DemandFlexibleLoadMeasuresData" DROP CONSTRAINT "DemandFlexibleLoadMeasuresData_parent_id_fkey", ADD CONSTRAINT "DemandFlexibleLoadMeasuresData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandFlexibleLoadMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandFuelSwitchingMeasurePackagesData" DROP CONSTRAINT "DemandFuelSwitchingMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "DemandFuelSwitchingMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "DemandFuelSwitchingMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "DemandFuelSwitchingMeasuresCost" DROP CONSTRAINT "DemandFuelSwitchingMeasuresCost_parent_id_fkey", ADD CONSTRAINT "DemandFuelSwitchingMeasuresCost_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandFuelSwitchingMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandFuelSwitchingMeasuresCostData" DROP CONSTRAINT "DemandFuelSwitchingMeasuresCostData_parent_id_fkey", ADD CONSTRAINT "DemandFuelSwitchingMeasuresCostData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandFuelSwitchingMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandFuelSwitchingMeasuresEnergyIntensityData" DROP CONSTRAINT "DemandFuelSwitchingMeasuresEnergyIntensityData_parent_id_fkey", ADD CONSTRAINT "DemandFuelSwitchingMeasuresEnergyIntensityData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandFuelSwitchingMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandFuelSwitchingMeasuresImpact" DROP CONSTRAINT "DemandFuelSwitchingMeasuresImpact_parent_id_fkey", ADD CONSTRAINT "DemandFuelSwitchingMeasuresImpact_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandFuelSwitchingMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandFuelSwitchingMeasuresImpactData" DROP CONSTRAINT "DemandFuelSwitchingMeasuresImpactData_parent_id_fkey", ADD CONSTRAINT "DemandFuelSwitchingMeasuresImpactData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandFuelSwitchingMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandSalesMeasurePackagesData" DROP CONSTRAINT "DemandSalesMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "DemandSalesMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "DemandSalesMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "DemandServiceDemandMeasurePackagesData" DROP CONSTRAINT "DemandServiceDemandMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "DemandServiceDemandMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "DemandServiceDemandMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "DemandServiceDemandMeasuresCost" DROP CONSTRAINT "DemandServiceDemandMeasuresCost_parent_id_fkey", ADD CONSTRAINT "DemandServiceDemandMeasuresCost_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandServiceDemandMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandServiceDemandMeasuresCostData" DROP CONSTRAINT "DemandServiceDemandMeasuresCostData_parent_id_fkey", ADD CONSTRAINT "DemandServiceDemandMeasuresCostData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandServiceDemandMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandServiceDemandMeasuresData" DROP CONSTRAINT "DemandServiceDemandMeasuresData_parent_id_fkey", ADD CONSTRAINT "DemandServiceDemandMeasuresData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandServiceDemandMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "DemandStockMeasurePackagesData" DROP CONSTRAINT "DemandStockMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "DemandStockMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "DemandStockMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "DemandStockMeasuresData" DROP CONSTRAINT "DemandStockMeasuresData_parent_id_fkey", ADD CONSTRAINT "DemandStockMeasuresData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "DemandStockMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "SupplyCasesData" DROP CONSTRAINT "SupplyCasesData_supply_case_id_fkey", ADD CONSTRAINT "SupplyCasesData_supply_case_id_fkey" FOREIGN KEY (supply_case_id) REFERENCES "SupplyCases"(id) ON DELETE CASCADE;
ALTER TABLE "SupplyExportMeasurePackagesData" DROP CONSTRAINT "SupplyExportMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "SupplyExportMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "SupplyExportMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "SupplyExportMeasuresData" DROP CONSTRAINT "SupplyExportMeasuresData_parent_id_fkey", ADD CONSTRAINT "SupplyExportMeasuresData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "SupplyExportMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "SupplySalesMeasurePackagesData" DROP CONSTRAINT "SupplySalesMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "SupplySalesMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "SupplySalesMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "SupplySalesMeasuresData" DROP CONSTRAINT "SupplySalesMeasuresData_parent_id_fkey", ADD CONSTRAINT "SupplySalesMeasuresData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "SupplySalesMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "SupplySalesShareMeasurePackagesData" DROP CONSTRAINT "SupplySalesShareMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "SupplySalesShareMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "SupplySalesShareMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "SupplySalesShareMeasuresData" DROP CONSTRAINT "SupplySalesShareMeasuresData_parent_id_fkey", ADD CONSTRAINT "SupplySalesShareMeasuresData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "SupplySalesShareMeasures"(id) ON DELETE CASCADE;
ALTER TABLE "SupplyStockMeasurePackagesData" DROP CONSTRAINT "SupplyStockMeasurePackagesData_package_id_fkey", ADD CONSTRAINT "SupplyStockMeasurePackagesData_package_id_fkey" FOREIGN KEY (package_id) REFERENCES "SupplyStockMeasurePackages"(id) ON DELETE CASCADE;
ALTER TABLE "SupplyStockMeasuresData" DROP CONSTRAINT "SupplyStockMeasuresData_parent_id_fkey", ADD CONSTRAINT "SupplyStockMeasuresData_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES "SupplyStockMeasures"(id) ON DELETE CASCADE;
