MappedCols = {
    "CO2PriceMeasures" : ['interpolation_method', 'geography', 'geography_map_key', 'extrapolation_method'],
    "DemandDriversData" : ['oth_2', 'parent', 'gau', 'oth_1'],
    "BlendNodeInputsData" : ['blend_node', 'supply_node'],
    "CurrenciesConversion" : ['currency'],
    "GeographiesData" : ['geography'],
    "DemandSectors" : ['shape'],
    "DemandTechsFixedMaintenanceCostData" : ['oth_2', 'gau', 'oth_1'],
    "DemandTechsAuxEfficiencyData" : ['oth_2', 'gau', 'oth_1'],
    "FinalEnergy" : ['shape'],
    "DemandTechsAuxEfficiency" : ['other_index_1', 'age_growth_or_decay_type', 'extrapolation_method', 'definition', 'interpolation_method', 'geography', 'other_index_2', 'demand_technology', 'shape', 'demand_tech_efficiency_types', 'final_energy'],
    "DemandTechsFuelSwitchCostData" : ['oth_2', 'gau', 'oth_1'],
    "DemandTechsFixedMaintenanceCost" : ['definition', 'age_growth_or_decay_type', 'extrapolation_method', 'other_index_1', 'currency', 'interpolation_method', 'geography', 'other_index_2', 'demand_technology'],
    "DemandTechsFuelSwitchCost" : ['definition', 'extrapolation_method', 'other_index_1', 'currency', 'interpolation_method', 'geography', 'other_index_2', 'demand_technology'],
    "DemandTechsInstallationCost" : ['definition', 'extrapolation_method', 'other_index_1', 'currency', 'interpolation_method', 'geography', 'other_index_2', 'demand_technology'],
    "DemandTechsInstallationCostNewData" : ['oth_2', 'gau', 'oth_1'],
    "DemandTechsParasiticEnergyData" : ['oth_2', 'gau', 'final_energy', 'oth_1'],
    "DemandTechsParasiticEnergy" : ['other_index_1', 'age_growth_or_decay_type', 'extrapolation_method', 'definition', 'interpolation_method', 'geography', 'other_index_2', 'demand_technology'],
    "DemandEnergyDemandsData" : ['oth_2', 'subsector', 'gau', 'final_energy', 'oth_1'],
    "DemandEnergyDemands" : ['other_index_1', 'driver_denominator_1', 'extrapolation_method', 'interpolation_method', 'driver_2', 'subsector', 'input_type', 'geography', 'geography_map_key', 'other_index_2', 'driver_1', 'driver_denominator_2'],
    "DemandEnergyEfficiencyMeasures" : ['other_index_1', 'stock_decay_function', 'extrapolation_method', 'input_type', 'subsector', 'interpolation_method', 'geography', 'other_index_2'],
    "DemandTechsMainEfficiency" : ['other_index_1', 'age_growth_or_decay_type', 'extrapolation_method', 'demand_tech_efficiency_types', 'definition', 'interpolation_method', 'geography', 'geography_map_key', 'other_index_2', 'demand_technology', 'final_energy'],
    "DemandFuelSwitchingMeasures" : ['subsector', 'final_energy_to', 'final_energy_from', 'stock_decay_function'],
    "DemandServiceDemandMeasures" : ['other_index_1', 'stock_decay_function', 'extrapolation_method', 'input_type', 'subsector', 'interpolation_method', 'geography', 'other_index_2'],
    "DemandSalesShareMeasures" : ['replaced_demand_tech', 'other_index_1', 'extrapolation_method', 'input_type', 'subsector', 'interpolation_method', 'geography', 'demand_technology'],
    "DemandSales" : ['other_index_1', 'extrapolation_method', 'input_type', 'subsector', 'interpolation_method', 'geography', 'other_index_2'],
    "DemandFlexibleLoadMeasures" : ['subsector', 'interpolation_method', 'geography', 'extrapolation_method', 'other_index_1'],
    "DemandEnergyEfficiencyMeasuresData" : ['oth_2', 'parent', 'gau', 'final_energy', 'oth_1'],
    "DemandEnergyEfficiencyMeasuresCost" : ['other_index_1', 'extrapolation_method', 'parent', 'currency', 'interpolation_method', 'geography', 'other_index_2'],
    "DemandFuelSwitchingMeasuresImpact" : ['other_index_1', 'extrapolation_method', 'parent', 'input_type', 'interpolation_method', 'geography', 'other_index_2'],
    "DemandFuelSwitchingMeasuresCost" : ['other_index_1', 'extrapolation_method', 'parent', 'currency', 'interpolation_method', 'geography', 'other_index_2'],
    "DemandFuelSwitchingMeasuresEnergyIntensity" : ['other_index_1', 'extrapolation_method', 'parent', 'interpolation_method', 'geography', 'other_index_2'],
    "DemandFuelSwitchingMeasuresEnergyIntensityData" : ['oth_2', 'parent', 'gau', 'oth_1'],
    "DemandFuelSwitchingMeasuresImpactData" : ['oth_2', 'parent', 'gau', 'oth_1'],
    "DemandSalesData" : ['oth_2', 'gau', 'demand_technology', 'oth_1'],
    "DemandSalesShareMeasuresData" : ['parent', 'gau', 'oth_1'],
    "DemandServiceLink" : ['subsector', 'linked_subsector'],
    "DemandServiceEfficiencyData" : ['oth_2', 'subsector', 'gau', 'final_energy', 'oth_1'],
    "DemandStockMeasures" : ['other_index_1', 'extrapolation_method', 'subsector', 'interpolation_method', 'geography', 'demand_technology'],
    "DemandStock" : ['other_index_1', 'driver_denominator_1', 'extrapolation_method', 'interpolation_method', 'driver_2', 'demand_stock_unit_type', 'subsector', 'input_type', 'geography', 'geography_map_key', 'other_index_2', 'driver_1', 'driver_denominator_2'],
    "DemandTechsCapitalCostReplacementData" : ['oth_2', 'gau', 'oth_1'],
    "DemandServiceDemands" : ['other_index_1', 'driver_denominator_1', 'extrapolation_method', 'interpolation_method', 'driver_2', 'subsector', 'input_type', 'geography', 'geography_map_key', 'other_index_2', 'driver_1', 'driver_denominator_2'],
    "DemandServiceEfficiency" : ['other_index_1', 'extrapolation_method', 'subsector', 'interpolation_method', 'geography', 'geography_map_key', 'other_index_2'],
    "DemandServiceDemandMeasuresData" : ['oth_2', 'parent', 'gau', 'oth_1'],
    "DemandStockMeasuresData" : ['parent', 'gau', 'oth_1'],
    "DemandTechsServiceLink" : ['other_index_1', 'age_growth_or_decay_type', 'service_link', 'extrapolation_method', 'definition', 'interpolation_method', 'geography', 'other_index_2', 'demand_technology'],
    "DispatchTransmissionConstraint" : ['interpolation_method', 'extrapolation_method'],
    "DemandTechsInstallationCostReplacementData" : ['oth_2', 'gau', 'oth_1'],
    "DemandTechsServiceDemandModifier" : ['other_index_1', 'age_growth_or_decay_type', 'extrapolation_method', 'interpolation_method', 'geography', 'other_index_2', 'demand_technology'],
    "DispatchFeedersAllocation" : ['input_type', 'interpolation_method', 'geography', 'geography_map_key', 'extrapolation_method'],
    "DispatchFeedersAllocationData" : ['demand_sector', 'gau'],
    "DispatchNodeConfig" : ['geography', 'dispatch_window', 'supply_node'],
    "DispatchTransmissionHurdleRate" : ['gau_to', 'parent', 'day_type', 'gau_from'],
    "DispatchTransmissionConstraintData" : ['gau_to', 'parent', 'day_type', 'gau_from'],
    "ImportCost" : ['currency', 'import_node', 'geography', 'extrapolation_method', 'interpolation_method'],
    "OtherIndexesData_copy" : ['other_index'],
    "ImportCostData" : ['demand_sector', 'gau'],
    "ShapesData" : ['dispatch_constraint', 'dispatch_feeder', 'gau', 'parent', 'timeshift_type', 'day_type'],
    "SupplyEmissionsData" : ['ghg_type', 'demand_sector', 'gau', 'ghg', 'oth_1'],
    "SupplyPotentialConversionData" : ['gau', 'oth_1'],
    "Shapes" : ['other_index_1', 'extrapolation_method', 'shape_type', 'input_type', 'interpolation_method', 'geography', 'geography_map_key', 'other_index_2', 'shape_unit_type'],
    "InflationConversion" : ['currency'],
    "SupplyCost" : ['currency', 'interpolation_method', 'geography', 'extrapolation_method', 'supply_node'],
    "StorageTechsEnergyCapitalCostReplacementData" : ['oth_2', 'gau', 'oth_1'],
    "SupplyTechs" : ['shape', 'stock_decay_function', 'supply_node'],
    "StorageTechsEnergyCapitalCost" : ['definition', 'supply_tech', 'extrapolation_method', 'reference_tech', 'currency', 'interpolation_method', 'geography'],
    "SupplyTechsFixedMaintenanceCost" : ['definition', 'age_growth_or_decay_type', 'extrapolation_method', 'supply_tech', 'currency', 'interpolation_method', 'geography'],
    "SupplyCostData" : ['parent', 'demand_sector', 'gau'],
    "SupplyTechsFixedMaintenanceCostData" : ['demand_sector', 'gau'],
    "StorageTechsCapacityCapitalCost" : ['definition', 'supply_tech', 'extrapolation_method', 'reference_tech', 'currency', 'interpolation_method', 'geography'],
    "StorageTechsEnergyCapitalCostNewData" : ['oth_2', 'gau', 'oth_1'],
    "SupplyTechsCapitalCost" : ['definition', 'supply_tech', 'extrapolation_method', 'currency', 'interpolation_method', 'geography', 'geography_map_key'],
    "SupplyTechsEfficiency" : ['age_growth_or_decay_type', 'extrapolation_method', 'supply_tech', 'definition', 'interpolation_method', 'geography'],
    "SupplyTechsInstallationCost" : ['definition', 'supply_tech', 'extrapolation_method', 'currency', 'interpolation_method', 'geography'],
    "SupplyTechsVariableMaintenanceCost" : ['definition', 'age_growth_or_decay_type', 'extrapolation_method', 'supply_tech', 'currency', 'interpolation_method', 'geography'],
    "SupplyTechsVariableMaintenanceCostData" : ['demand_sector', 'gau'],
    "SupplyTechsInstallationCostNewData" : ['demand_sector', 'gau'],
    "SupplyEfficiency" : ['interpolation_method', 'geography', 'extrapolation_method', 'name'],
    "SupplyCapacityFactor" : ['supply_node', 'interpolation_method', 'age_growth_or_decay_type', 'extrapolation_method', 'geography'],
    "SupplyTechsEfficiencyData" : ['demand_sector', 'efficiency_type', 'gau', 'supply_node'],
    "SupplyExport" : ['interpolation_method', 'geography', 'extrapolation_method', 'supply_node', 'other_index_1'],
    "SupplyExportMeasures" : ['interpolation_method', 'geography', 'extrapolation_method', 'supply_node', 'other_index_1'],
    "SupplyPotentialConversion" : ['interpolation_method', 'geography', 'extrapolation_method', 'supply_node', 'other_index_1'],
    "SupplyPotential" : ['other_index_1', 'extrapolation_method', 'supply_node', 'interpolation_method', 'geography', 'geography_map_key'],
    "SupplySalesData" : ['demand_sector', 'gau', 'supply_technology'],
    "SupplySalesMeasures" : ['other_index_1', 'extrapolation_method', 'supply_node', 'supply_technology', 'interpolation_method', 'geography', 'geography_map_key'],
    "SupplySalesShareMeasures" : ['other_index_1', 'extrapolation_method', 'supply_node', 'supply_technology', 'interpolation_method', 'geography', 'replaced_supply_technology'],
    "SupplySalesShare" : ['interpolation_method', 'geography', 'extrapolation_method', 'supply_node'],
    "SupplySalesShareData" : ['demand_sector', 'gau', 'supply_technology'],
    "SupplyPotentialData" : ['demand_sector', 'gau', 'oth_1'],
    "SupplySales" : ['interpolation_method', 'geography', 'geography_map_key', 'extrapolation_method', 'supply_node'],
    "SupplySalesMeasuresData" : ['parent', 'demand_sector', 'gau', 'oth_1'],
    "SupplySalesShareMeasuresData" : ['parent', 'demand_sector', 'gau', 'oth_1'],
    "SupplyStockMeasures" : ['other_index_1', 'extrapolation_method', 'supply_node', 'supply_technology', 'interpolation_method', 'geography', 'geography_map_key'],
    "SupplyTechsInstallationCostReplacementData" : ['demand_sector', 'gau'],
    "SupplyStock" : ['interpolation_method', 'geography', 'geography_map_key', 'extrapolation_method', 'supply_node'],
    "SupplyTechsCO2Capture" : ['age_growth_or_decay_type', 'extrapolation_method', 'supply_tech', 'definition', 'interpolation_method', 'geography'],
    "SupplyTechsCapacityFactor" : ['age_growth_or_decay_type', 'extrapolation_method', 'supply_tech', 'definition', 'interpolation_method', 'geography'],
    "SupplyTechsCapitalCostReplacementData" : ['demand_sector', 'gau'],
    "SupplyTechsCO2CaptureData" : ['gau'],
    "SupplyTechsCapacityFactorData" : ['gau', 'oth_1'],
    "DemandStockData" : ['oth_2', 'gau', 'demand_technology', 'oth_1'],
    "BlendNodeBlendMeasuresData" : ['parent', 'demand_sector', 'gau'],
    "DemandServiceDemandMeasuresCostData" : ['oth_2', 'parent', 'gau', 'oth_1'],
    "DemandCO2CaptureMeasures" : ['other_index_1', 'stock_decay_function', 'extrapolation_method', 'input_type', 'subsector', 'interpolation_method', 'geography', 'other_index_2'],
    "DemandFlexibleLoadMeasuresData" : ['parent', 'gau', 'demand_technology', 'oth_1'],
    "DemandDrivers" : ['other_index_1', 'extrapolation_method', 'base_driver', 'input_type', 'interpolation_method', 'geography', 'geography_map_key', 'other_index_2'],
    "BlendNodeBlendMeasures" : ['other_index_1', 'extrapolation_method', 'supply_node', 'interpolation_method', 'geography', 'blend_node'],
    "DemandTechsMainEfficiencyData" : ['oth_2', 'gau', 'oth_1'],
    "CO2PriceMeasuresData" : ['parent', 'gau'],
    "DemandFuelSwitchingMeasuresCostData" : ['oth_2', 'parent', 'gau', 'oth_1'],
    "DemandEnergyEfficiencyMeasuresCostData" : ['oth_2', 'parent', 'gau', 'final_energy', 'oth_1'],
    "DemandTechsServiceDemandModifierData" : ['oth_2', 'gau', 'oth_1'],
    "PrimaryCostData" : ['demand_sector', 'gau', 'oth_1'],
    "DemandTechsCapitalCost" : ['definition', 'extrapolation_method', 'other_index_1', 'currency', 'interpolation_method', 'geography', 'other_index_2', 'demand_technology'],
    "DemandSubsectors" : ['shape', 'sector'],
    "DemandTechs" : ['subsector', 'linked', 'stock_decay_function', 'demand_tech_unit_type', 'shape'],
    "DemandServiceDemandMeasuresCost" : ['other_index_1', 'extrapolation_method', 'parent', 'currency', 'interpolation_method', 'geography', 'other_index_2'],
    "DemandServiceDemandsData" : ['oth_2', 'oth_1', 'final_energy', 'demand_technology', 'gau'],
    "DemandTechsCapitalCostNewData" : ['oth_2', 'gau', 'oth_1'],
    "DemandTechsServiceLinkData" : ['oth_2', 'gau', 'oth_1'],
    "StorageTechsCapacityCapitalCostNewData" : ['oth_2', 'gau', 'oth_1'],
    "PrimaryCost" : ['other_index_1', 'extrapolation_method', 'primary_node', 'currency', 'interpolation_method', 'geography'],
    "OtherIndexesData" : ['other_index'],
    "SupplyNodes" : ['stock_decay_function', 'tradable_geography', 'supply_type', 'geography_map_key', 'residual_supply_node', 'final_energy_link', 'shape'],
    "StorageTechsCapacityCapitalCostReplacementData" : ['oth_2', 'gau', 'oth_1'],
    "SupplyCapacityFactorData" : ['demand_sector', 'gau'],
    "SupplyEfficiencyData" : ['demand_sector', 'efficiency_type', 'gau', 'supply_node'],
    "SupplyEmissions" : ['interpolation_method', 'geography', 'extrapolation_method', 'supply_node', 'other_index_1'],
    "SupplyExportData" : ['gau', 'oth_1'],
    "SupplyExportMeasuresData" : ['parent', 'gau', 'oth_1'],
    "SupplyStockData" : ['demand_sector', 'gau', 'supply_technology'],
    "SupplyStockMeasuresData" : ['parent', 'demand_sector', 'gau', 'oth_1'],
    "SupplyTechsCapitalCostNewData" : ['demand_sector', 'gau'],
}
