-- NOTE: Users should not need to run this script unless instructed by Evolved Energy Research, as it has likely
-- already been run on the database you received.
-- This sql script adds a number of NOT NULL constraints to various Data tables in the Pathways database.
-- It also deletes rows with a NULL in the "value", "year" or "vintage" column from each table first in an effort
-- to get rid of unhelpful rows that might prevent the addition of the constraint.
-- Recommended usage:
-- psql -a database_name < add_data_table_not_null_constraints.sql
BEGIN;
DELETE FROM "BlendNodeBlendMeasuresData" WHERE value IS NULL;
DELETE FROM "BlendNodeBlendMeasuresData" WHERE year IS NULL;
DELETE FROM "DemandDriversData" WHERE value IS NULL;
DELETE FROM "DemandDriversData" WHERE year IS NULL;
DELETE FROM "DemandEnergyDemandsData" WHERE value IS NULL;
DELETE FROM "DemandEnergyDemandsData" WHERE year IS NULL;
DELETE FROM "DemandEnergyEfficiencyMeasuresCostData" WHERE value IS NULL;
DELETE FROM "DemandEnergyEfficiencyMeasuresCostData" WHERE vintage IS NULL;
DELETE FROM "DemandEnergyEfficiencyMeasuresData" WHERE value IS NULL;
DELETE FROM "DemandEnergyEfficiencyMeasuresData" WHERE year IS NULL;
DELETE FROM "DemandFlexibleLoadMeasuresData" WHERE value IS NULL;
DELETE FROM "DemandFlexibleLoadMeasuresData" WHERE year IS NULL;
DELETE FROM "DemandFuelSwitchingMeasuresCostData" WHERE value IS NULL;
DELETE FROM "DemandFuelSwitchingMeasuresCostData" WHERE vintage IS NULL;
DELETE FROM "DemandFuelSwitchingMeasuresEnergyIntensityData" WHERE value IS NULL;
DELETE FROM "DemandFuelSwitchingMeasuresEnergyIntensityData" WHERE year IS NULL;
DELETE FROM "DemandFuelSwitchingMeasuresImpactData" WHERE value IS NULL;
DELETE FROM "DemandFuelSwitchingMeasuresImpactData" WHERE year IS NULL;
DELETE FROM "DemandSalesData" WHERE value IS NULL;
DELETE FROM "DemandSalesData" WHERE vintage IS NULL;
DELETE FROM "DemandSalesMeasuresData" WHERE value IS NULL;
DELETE FROM "DemandSalesMeasuresData" WHERE vintage IS NULL;
DELETE FROM "DemandServiceDemandMeasuresCostData" WHERE value IS NULL;
DELETE FROM "DemandServiceDemandMeasuresCostData" WHERE vintage IS NULL;
DELETE FROM "DemandServiceDemandMeasuresData" WHERE value IS NULL;
DELETE FROM "DemandServiceDemandMeasuresData" WHERE year IS NULL;
DELETE FROM "DemandServiceDemandsData" WHERE value IS NULL;
DELETE FROM "DemandServiceDemandsData" WHERE year IS NULL;
DELETE FROM "DemandServiceEfficiencyData" WHERE value IS NULL;
DELETE FROM "DemandServiceEfficiencyData" WHERE year IS NULL;
DELETE FROM "DemandStockData" WHERE value IS NULL;
DELETE FROM "DemandStockData" WHERE year IS NULL;
DELETE FROM "DemandStockMeasuresData" WHERE value IS NULL;
DELETE FROM "DemandStockMeasuresData" WHERE year IS NULL;
DELETE FROM "DemandTechsAuxEfficiencyData" WHERE value IS NULL;
DELETE FROM "DemandTechsAuxEfficiencyData" WHERE vintage IS NULL;
DELETE FROM "DemandTechsCapitalCostNewData" WHERE value IS NULL;
DELETE FROM "DemandTechsCapitalCostNewData" WHERE vintage IS NULL;
DELETE FROM "DemandTechsCapitalCostReplacementData" WHERE value IS NULL;
DELETE FROM "DemandTechsCapitalCostReplacementData" WHERE vintage IS NULL;
DELETE FROM "DemandTechsFixedMaintenanceCostData" WHERE value IS NULL;
DELETE FROM "DemandTechsFixedMaintenanceCostData" WHERE vintage IS NULL;
DELETE FROM "DemandTechsFuelSwitchCostData" WHERE value IS NULL;
DELETE FROM "DemandTechsFuelSwitchCostData" WHERE vintage IS NULL;
DELETE FROM "DemandTechsInstallationCostNewData" WHERE value IS NULL;
DELETE FROM "DemandTechsInstallationCostNewData" WHERE vintage IS NULL;
DELETE FROM "DemandTechsInstallationCostReplacementData" WHERE value IS NULL;
DELETE FROM "DemandTechsInstallationCostReplacementData" WHERE vintage IS NULL;
DELETE FROM "DemandTechsMainEfficiencyData" WHERE value IS NULL;
DELETE FROM "DemandTechsMainEfficiencyData" WHERE vintage IS NULL;
DELETE FROM "DemandTechsParasiticEnergyData" WHERE value IS NULL;
DELETE FROM "DemandTechsParasiticEnergyData" WHERE vintage IS NULL;
DELETE FROM "DemandTechsServiceDemandModifierData" WHERE value IS NULL;
DELETE FROM "DemandTechsServiceDemandModifierData" WHERE vintage IS NULL;
DELETE FROM "DemandTechsServiceLinkData" WHERE value IS NULL;
DELETE FROM "DemandTechsServiceLinkData" WHERE vintage IS NULL;
DELETE FROM "DispatchFeedersAllocationData" WHERE value IS NULL;
DELETE FROM "DispatchFeedersAllocationData" WHERE year IS NULL;
DELETE FROM "ImportCostData" WHERE value IS NULL;
DELETE FROM "ImportCostData" WHERE year IS NULL;
DELETE FROM "PrimaryCostData" WHERE value IS NULL;
DELETE FROM "PrimaryCostData" WHERE year IS NULL;
DELETE FROM "ShapesData" WHERE value IS NULL;
DELETE FROM "StorageTechsCapacityCapitalCostNewData" WHERE value IS NULL;
DELETE FROM "StorageTechsCapacityCapitalCostNewData" WHERE vintage IS NULL;
DELETE FROM "StorageTechsCapacityCapitalCostReplacementData" WHERE value IS NULL;
DELETE FROM "StorageTechsCapacityCapitalCostReplacementData" WHERE vintage IS NULL;
DELETE FROM "StorageTechsEnergyCapitalCostNewData" WHERE value IS NULL;
DELETE FROM "StorageTechsEnergyCapitalCostNewData" WHERE vintage IS NULL;
DELETE FROM "StorageTechsEnergyCapitalCostReplacementData" WHERE value IS NULL;
DELETE FROM "StorageTechsEnergyCapitalCostReplacementData" WHERE vintage IS NULL;
DELETE FROM "SupplyCapacityFactorData" WHERE value IS NULL;
DELETE FROM "SupplyCapacityFactorData" WHERE year IS NULL;
DELETE FROM "SupplyCostData" WHERE value IS NULL;
DELETE FROM "SupplyCostData" WHERE year IS NULL;
DELETE FROM "SupplyEfficiencyData" WHERE value IS NULL;
DELETE FROM "SupplyEfficiencyData" WHERE year IS NULL;
DELETE FROM "SupplyEmissionsData" WHERE value IS NULL;
DELETE FROM "SupplyEmissionsData" WHERE year IS NULL;
DELETE FROM "SupplyExportData" WHERE value IS NULL;
DELETE FROM "SupplyExportData" WHERE year IS NULL;
DELETE FROM "SupplyExportMeasuresData" WHERE value IS NULL;
DELETE FROM "SupplyExportMeasuresData" WHERE year IS NULL;
DELETE FROM "SupplyPotentialConversionData" WHERE value IS NULL;
DELETE FROM "SupplyPotentialConversionData" WHERE year IS NULL;
DELETE FROM "SupplyPotentialData" WHERE value IS NULL;
DELETE FROM "SupplyPotentialData" WHERE year IS NULL;
DELETE FROM "SupplySalesData" WHERE value IS NULL;
DELETE FROM "SupplySalesData" WHERE vintage IS NULL;
DELETE FROM "SupplySalesMeasuresData" WHERE value IS NULL;
DELETE FROM "SupplySalesMeasuresData" WHERE vintage IS NULL;
DELETE FROM "SupplySalesShareData" WHERE value IS NULL;
DELETE FROM "SupplySalesShareData" WHERE vintage IS NULL;
DELETE FROM "SupplySalesShareMeasuresData" WHERE value IS NULL;
DELETE FROM "SupplySalesShareMeasuresData" WHERE vintage IS NULL;
DELETE FROM "SupplyStockData" WHERE value IS NULL;
DELETE FROM "SupplyStockData" WHERE year IS NULL;
DELETE FROM "SupplyStockMeasuresData" WHERE value IS NULL;
DELETE FROM "SupplyStockMeasuresData" WHERE year IS NULL;
DELETE FROM "SupplyTechsCapacityFactorData" WHERE value IS NULL;
DELETE FROM "SupplyTechsCapacityFactorData" WHERE vintage IS NULL;
DELETE FROM "SupplyTechsCapitalCostNewData" WHERE value IS NULL;
DELETE FROM "SupplyTechsCapitalCostNewData" WHERE vintage IS NULL;
DELETE FROM "SupplyTechsCapitalCostReplacementData" WHERE value IS NULL;
DELETE FROM "SupplyTechsCapitalCostReplacementData" WHERE vintage IS NULL;
DELETE FROM "SupplyTechsCO2CaptureData" WHERE value IS NULL;
DELETE FROM "SupplyTechsCO2CaptureData" WHERE vintage IS NULL;
DELETE FROM "SupplyTechsEfficiencyData" WHERE value IS NULL;
DELETE FROM "SupplyTechsEfficiencyData" WHERE vintage IS NULL;
DELETE FROM "SupplyTechsFixedMaintenanceCostData" WHERE value IS NULL;
DELETE FROM "SupplyTechsFixedMaintenanceCostData" WHERE vintage IS NULL;
DELETE FROM "SupplyTechsInstallationCostNewData" WHERE value IS NULL;
DELETE FROM "SupplyTechsInstallationCostNewData" WHERE vintage IS NULL;
DELETE FROM "SupplyTechsInstallationCostReplacementData" WHERE value IS NULL;
DELETE FROM "SupplyTechsInstallationCostReplacementData" WHERE vintage IS NULL;
DELETE FROM "SupplyTechsVariableMaintenanceCostData" WHERE value IS NULL;
DELETE FROM "SupplyTechsVariableMaintenanceCostData" WHERE vintage IS NULL;
ALTER TABLE "BlendNodeBlendMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "BlendNodeBlendMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "BlendNodeBlendMeasuresData" ALTER gau_id SET NOT NULL;
ALTER TABLE "BlendNodeBlendMeasuresData" ALTER parent_id SET NOT NULL;
ALTER TABLE "BlendNodeBlendMeasuresData" ALTER value SET NOT NULL;
ALTER TABLE "BlendNodeBlendMeasuresData" ALTER year SET NOT NULL;
ALTER TABLE "BlendNodeInputsData" ALTER blend_node_id SET NOT NULL;
ALTER TABLE "BlendNodeInputsData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "DemandDriversData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandDriversData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandDriversData" ALTER value SET NOT NULL;
ALTER TABLE "DemandDriversData" ALTER year SET NOT NULL;
ALTER TABLE "DemandEnergyDemandsData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandEnergyDemandsData" ALTER subsector_id SET NOT NULL;
ALTER TABLE "DemandEnergyDemandsData" ALTER value SET NOT NULL;
ALTER TABLE "DemandEnergyDemandsData" ALTER year SET NOT NULL;
ALTER TABLE "DemandEnergyEfficiencyMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "DemandEnergyEfficiencyMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "DemandEnergyEfficiencyMeasuresCostData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandEnergyEfficiencyMeasuresCostData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandEnergyEfficiencyMeasuresCostData" ALTER value SET NOT NULL;
ALTER TABLE "DemandEnergyEfficiencyMeasuresCostData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandEnergyEfficiencyMeasuresData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandEnergyEfficiencyMeasuresData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandEnergyEfficiencyMeasuresData" ALTER value SET NOT NULL;
ALTER TABLE "DemandEnergyEfficiencyMeasuresData" ALTER year SET NOT NULL;
ALTER TABLE "DemandFlexibleLoadMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "DemandFlexibleLoadMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "DemandFlexibleLoadMeasuresData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandFlexibleLoadMeasuresData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandFlexibleLoadMeasuresData" ALTER value SET NOT NULL;
ALTER TABLE "DemandFlexibleLoadMeasuresData" ALTER year SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresCostData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresCostData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresCostData" ALTER value SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresCostData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresEnergyIntensityData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresEnergyIntensityData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresEnergyIntensityData" ALTER value SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresEnergyIntensityData" ALTER year SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresImpactData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresImpactData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresImpactData" ALTER value SET NOT NULL;
ALTER TABLE "DemandFuelSwitchingMeasuresImpactData" ALTER year SET NOT NULL;
ALTER TABLE "DemandSalesData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandSalesData" ALTER subsector_id SET NOT NULL;
ALTER TABLE "DemandSalesData" ALTER value SET NOT NULL;
ALTER TABLE "DemandSalesData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandSalesMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "DemandSalesMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "DemandSalesMeasuresData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandSalesMeasuresData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandSalesMeasuresData" ALTER value SET NOT NULL;
ALTER TABLE "DemandSalesMeasuresData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandServiceDemandMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "DemandServiceDemandMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "DemandServiceDemandMeasuresCostData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandServiceDemandMeasuresCostData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandServiceDemandMeasuresCostData" ALTER value SET NOT NULL;
ALTER TABLE "DemandServiceDemandMeasuresCostData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandServiceDemandMeasuresData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandServiceDemandMeasuresData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandServiceDemandMeasuresData" ALTER value SET NOT NULL;
ALTER TABLE "DemandServiceDemandMeasuresData" ALTER year SET NOT NULL;
ALTER TABLE "DemandServiceDemandsData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandServiceDemandsData" ALTER subsector_id SET NOT NULL;
ALTER TABLE "DemandServiceDemandsData" ALTER value SET NOT NULL;
ALTER TABLE "DemandServiceDemandsData" ALTER year SET NOT NULL;
ALTER TABLE "DemandServiceEfficiencyData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandServiceEfficiencyData" ALTER subsector_id SET NOT NULL;
ALTER TABLE "DemandServiceEfficiencyData" ALTER value SET NOT NULL;
ALTER TABLE "DemandServiceEfficiencyData" ALTER year SET NOT NULL;
ALTER TABLE "DemandStockData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandStockData" ALTER subsector_id SET NOT NULL;
ALTER TABLE "DemandStockData" ALTER value SET NOT NULL;
ALTER TABLE "DemandStockData" ALTER year SET NOT NULL;
ALTER TABLE "DemandStockMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "DemandStockMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "DemandStockMeasuresData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandStockMeasuresData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandStockMeasuresData" ALTER value SET NOT NULL;
ALTER TABLE "DemandStockMeasuresData" ALTER year SET NOT NULL;
ALTER TABLE "DemandTechsAuxEfficiencyData" ALTER demand_technology_id SET NOT NULL;
ALTER TABLE "DemandTechsAuxEfficiencyData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsAuxEfficiencyData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsAuxEfficiencyData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandTechsCapitalCostNewData" ALTER demand_technology_id SET NOT NULL;
ALTER TABLE "DemandTechsCapitalCostNewData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsCapitalCostNewData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsCapitalCostNewData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandTechsCapitalCostReplacementData" ALTER demand_technology_id SET NOT NULL;
ALTER TABLE "DemandTechsCapitalCostReplacementData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsCapitalCostReplacementData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsCapitalCostReplacementData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandTechsFixedMaintenanceCostData" ALTER demand_technology_id SET NOT NULL;
ALTER TABLE "DemandTechsFixedMaintenanceCostData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsFixedMaintenanceCostData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsFixedMaintenanceCostData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandTechsFuelSwitchCostData" ALTER demand_technology_id SET NOT NULL;
ALTER TABLE "DemandTechsFuelSwitchCostData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsFuelSwitchCostData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsFuelSwitchCostData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandTechsInstallationCostNewData" ALTER demand_technology_id SET NOT NULL;
ALTER TABLE "DemandTechsInstallationCostNewData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsInstallationCostNewData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsInstallationCostNewData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandTechsInstallationCostReplacementData" ALTER demand_technology_id SET NOT NULL;
ALTER TABLE "DemandTechsInstallationCostReplacementData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsInstallationCostReplacementData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsInstallationCostReplacementData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandTechsMainEfficiencyData" ALTER demand_technology_id SET NOT NULL;
ALTER TABLE "DemandTechsMainEfficiencyData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsMainEfficiencyData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsMainEfficiencyData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandTechsParasiticEnergyData" ALTER demand_technology_id SET NOT NULL;
ALTER TABLE "DemandTechsParasiticEnergyData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsParasiticEnergyData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsParasiticEnergyData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandTechsServiceDemandModifierData" ALTER demand_technology_id SET NOT NULL;
ALTER TABLE "DemandTechsServiceDemandModifierData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsServiceDemandModifierData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsServiceDemandModifierData" ALTER vintage SET NOT NULL;
ALTER TABLE "DemandTechsServiceLinkData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DemandTechsServiceLinkData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DemandTechsServiceLinkData" ALTER value SET NOT NULL;
ALTER TABLE "DemandTechsServiceLinkData" ALTER vintage SET NOT NULL;
ALTER TABLE "DispatchFeedersAllocationData" ALTER dispatch_feeder_id SET NOT NULL;
ALTER TABLE "DispatchFeedersAllocationData" ALTER gau_id SET NOT NULL;
ALTER TABLE "DispatchFeedersAllocationData" ALTER parent_id SET NOT NULL;
ALTER TABLE "DispatchFeedersAllocationData" ALTER value SET NOT NULL;
ALTER TABLE "DispatchFeedersAllocationData" ALTER year SET NOT NULL;
ALTER TABLE "GeographiesData" ALTER geography_id SET NOT NULL;
ALTER TABLE "GeographiesData" ALTER name SET NOT NULL;
ALTER TABLE "ImportCostData" ALTER gau_id SET NOT NULL;
ALTER TABLE "ImportCostData" ALTER import_node_id SET NOT NULL;
ALTER TABLE "ImportCostData" ALTER value SET NOT NULL;
ALTER TABLE "ImportCostData" ALTER year SET NOT NULL;
ALTER TABLE "OtherIndexesData" ALTER name SET NOT NULL;
ALTER TABLE "OtherIndexesData" ALTER other_index_id SET NOT NULL;
ALTER TABLE "PrimaryCostData" ALTER gau_id SET NOT NULL;
ALTER TABLE "PrimaryCostData" ALTER primary_node_id SET NOT NULL;
ALTER TABLE "PrimaryCostData" ALTER value SET NOT NULL;
ALTER TABLE "PrimaryCostData" ALTER year SET NOT NULL;
ALTER TABLE "ShapesData" ALTER gau_id SET NOT NULL;
ALTER TABLE "ShapesData" ALTER parent_id SET NOT NULL;
ALTER TABLE "ShapesData" ALTER value SET NOT NULL;
ALTER TABLE "StorageTechsCapacityCapitalCostNewData" ALTER gau_id SET NOT NULL;
ALTER TABLE "StorageTechsCapacityCapitalCostNewData" ALTER value SET NOT NULL;
ALTER TABLE "StorageTechsCapacityCapitalCostNewData" ALTER vintage SET NOT NULL;
ALTER TABLE "StorageTechsCapacityCapitalCostReplacementData" ALTER gau_id SET NOT NULL;
ALTER TABLE "StorageTechsCapacityCapitalCostReplacementData" ALTER value SET NOT NULL;
ALTER TABLE "StorageTechsCapacityCapitalCostReplacementData" ALTER vintage SET NOT NULL;
ALTER TABLE "StorageTechsEnergyCapitalCostNewData" ALTER gau_id SET NOT NULL;
ALTER TABLE "StorageTechsEnergyCapitalCostNewData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "StorageTechsEnergyCapitalCostNewData" ALTER value SET NOT NULL;
ALTER TABLE "StorageTechsEnergyCapitalCostNewData" ALTER vintage SET NOT NULL;
ALTER TABLE "StorageTechsEnergyCapitalCostReplacementData" ALTER gau_id SET NOT NULL;
ALTER TABLE "StorageTechsEnergyCapitalCostReplacementData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "StorageTechsEnergyCapitalCostReplacementData" ALTER value SET NOT NULL;
ALTER TABLE "StorageTechsEnergyCapitalCostReplacementData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplyCapacityFactorData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyCapacityFactorData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "SupplyCapacityFactorData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyCapacityFactorData" ALTER year SET NOT NULL;
ALTER TABLE "SupplyCostData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyCostData" ALTER parent_id SET NOT NULL;
ALTER TABLE "SupplyCostData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyCostData" ALTER year SET NOT NULL;
ALTER TABLE "SupplyEfficiencyData" ALTER efficiency_type_id SET NOT NULL;
ALTER TABLE "SupplyEfficiencyData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyEfficiencyData" ALTER parent_id SET NOT NULL;
ALTER TABLE "SupplyEfficiencyData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "SupplyEfficiencyData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyEfficiencyData" ALTER year SET NOT NULL;
ALTER TABLE "SupplyEmissionsData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyEmissionsData" ALTER ghg_id SET NOT NULL;
ALTER TABLE "SupplyEmissionsData" ALTER ghg_type_id SET NOT NULL;
ALTER TABLE "SupplyEmissionsData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "SupplyEmissionsData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyEmissionsData" ALTER year SET NOT NULL;
ALTER TABLE "SupplyExportData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyExportData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "SupplyExportData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyExportData" ALTER year SET NOT NULL;
ALTER TABLE "SupplyExportMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "SupplyExportMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "SupplyExportMeasuresData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyExportMeasuresData" ALTER parent_id SET NOT NULL;
ALTER TABLE "SupplyExportMeasuresData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyExportMeasuresData" ALTER year SET NOT NULL;
ALTER TABLE "SupplyPotentialConversionData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyPotentialConversionData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "SupplyPotentialConversionData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyPotentialConversionData" ALTER year SET NOT NULL;
ALTER TABLE "SupplyPotentialData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyPotentialData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "SupplyPotentialData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyPotentialData" ALTER year SET NOT NULL;
ALTER TABLE "SupplySalesData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplySalesData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "SupplySalesData" ALTER value SET NOT NULL;
ALTER TABLE "SupplySalesData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplySalesMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "SupplySalesMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "SupplySalesMeasuresData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplySalesMeasuresData" ALTER parent_id SET NOT NULL;
ALTER TABLE "SupplySalesMeasuresData" ALTER value SET NOT NULL;
ALTER TABLE "SupplySalesMeasuresData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplySalesShareData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplySalesShareData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "SupplySalesShareData" ALTER value SET NOT NULL;
ALTER TABLE "SupplySalesShareData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplySalesShareMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "SupplySalesShareMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "SupplySalesShareMeasuresData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplySalesShareMeasuresData" ALTER parent_id SET NOT NULL;
ALTER TABLE "SupplySalesShareMeasuresData" ALTER value SET NOT NULL;
ALTER TABLE "SupplySalesShareMeasuresData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplyStockData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyStockData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "SupplyStockData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyStockData" ALTER year SET NOT NULL;
ALTER TABLE "SupplyStockMeasurePackagesData" ALTER measure_id SET NOT NULL;
ALTER TABLE "SupplyStockMeasurePackagesData" ALTER package_id SET NOT NULL;
ALTER TABLE "SupplyStockMeasuresData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyStockMeasuresData" ALTER parent_id SET NOT NULL;
ALTER TABLE "SupplyStockMeasuresData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyStockMeasuresData" ALTER year SET NOT NULL;
ALTER TABLE "SupplyTechsCapacityFactorData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyTechsCapacityFactorData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "SupplyTechsCapacityFactorData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyTechsCapacityFactorData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplyTechsCapitalCostNewData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyTechsCapitalCostNewData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "SupplyTechsCapitalCostNewData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyTechsCapitalCostNewData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplyTechsCapitalCostReplacementData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyTechsCapitalCostReplacementData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "SupplyTechsCapitalCostReplacementData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyTechsCapitalCostReplacementData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplyTechsCO2CaptureData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyTechsCO2CaptureData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "SupplyTechsCO2CaptureData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyTechsCO2CaptureData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplyTechsEfficiencyData" ALTER efficiency_type_id SET NOT NULL;
ALTER TABLE "SupplyTechsEfficiencyData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyTechsEfficiencyData" ALTER supply_node_id SET NOT NULL;
ALTER TABLE "SupplyTechsEfficiencyData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "SupplyTechsEfficiencyData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyTechsEfficiencyData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplyTechsFixedMaintenanceCostData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyTechsFixedMaintenanceCostData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "SupplyTechsFixedMaintenanceCostData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyTechsFixedMaintenanceCostData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplyTechsInstallationCostNewData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyTechsInstallationCostNewData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "SupplyTechsInstallationCostNewData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyTechsInstallationCostNewData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplyTechsInstallationCostReplacementData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyTechsInstallationCostReplacementData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "SupplyTechsInstallationCostReplacementData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyTechsInstallationCostReplacementData" ALTER vintage SET NOT NULL;
ALTER TABLE "SupplyTechsVariableMaintenanceCostData" ALTER gau_id SET NOT NULL;
ALTER TABLE "SupplyTechsVariableMaintenanceCostData" ALTER supply_tech_id SET NOT NULL;
ALTER TABLE "SupplyTechsVariableMaintenanceCostData" ALTER value SET NOT NULL;
ALTER TABLE "SupplyTechsVariableMaintenanceCostData" ALTER vintage SET NOT NULL;
COMMIT;